"""Deterministic Arabic-text-layer PDF builder for the fixture corpus.

Writes a minimal PDF whose text layer carries real Arabic codepoints, using a
Type0/Identity-H font with a ToUnicode CMap and no embedded font file — the
same shape a real Arabic PDF has, and the only part pdfium needs to extract
text. Glyphs are written in visual order (right to left) with paired
delimiters mirrored, as an Arabic producer writes them, so extraction yields
logical order back.

Lines are laid out the way Arabic actually sets: anchored at the **right**
margin and running leftwards. That matters — `paragraphs.page_paragraphs`
reads paragraph indents off the right edge and `headings.heading_tiers` reads
centring off the line box, so a fixture with left-anchored lines would exercise
the wrong geometry entirely.

The corpus is generated from this module rather than committed as binaries:
the fixtures stay reviewable in a diff, and `tests/snapshots/*.sha256` pins the
generated bytes so a change *here* shows up as a deliberate corpus change
rather than a silent one.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

#: Private-use codepoints: the signature of a legacy non-Unicode Arabic font
#: whose text layer renders correctly but carries no meaning.
PUA_START = 0xE000

#: Glyph advance as a fraction of the font size. Declared as `/DW 500` on the
#: descendant font, which is close to a real Arabic face's average advance and
#: keeps a full text line inside the page box.
ADVANCE = 0.5

#: Bidi mirroring: a reader renders `(` as `)` inside an RTL run, so an Arabic
#: producer stores the mirrored codepoint in the visual buffer. pdfium mirrors
#: back on extraction, and without this a fixture's `(١)` marker would come out
#: as `)١(` and never match footnotes.MARKER_RE.
_MIRRORED = str.maketrans("()[]{}<>", ")(][}{><")


@dataclass(frozen=True)
class Line:
    """One text run, positioned by its right edge (PDF points, y from bottom)."""

    text: str
    y: int
    size: float = 12.0
    #: "right" hugs the right margin; "center" centres on the page.
    align: str = "right"
    #: Points the right edge is inset from the right margin — a paragraph indent.
    indent: int = 0
    #: Written left-to-right without mirroring. Latin runs (URLs, folios) need this.
    ltr: bool = False

    def width(self) -> float:
        return len(self.text) * self.size * ADVANCE


@dataclass
class Page:
    lines: list[Line] = field(default_factory=list)
    width: int = 612
    height: int = 792
    right_margin: int = 540

    def x_of(self, line: Line) -> float:
        if line.align == "center":
            return (self.width - line.width()) / 2
        return self.right_margin - line.indent - line.width()


def to_pua(text: str) -> str:
    """Map letters onto the private-use area, keeping spaces.

    Produces the "fake text layer" case: a page whose codepoints carry no
    meaning at all, which `clean.bad_glyph_ratio` has to catch at any length.
    """
    return "".join(" " if ch.isspace() else chr(PUA_START + (ord(ch) % 0x400)) for ch in text)


def _content_stream(page: Page) -> bytes:
    ops: list[str] = []
    for line in page.lines:
        glyphs = line.text if line.ltr else line.text[::-1].translate(_MIRRORED)
        cids = "".join(f"{ord(c):04X}" for c in glyphs)
        ops.append(f"BT /F1 {line.size} Tf {page.x_of(line):.1f} {line.y} Td <{cids}> Tj ET")
    return "\n".join(ops).encode("latin-1")


def _tounicode(codepoints: set[int]) -> bytes:
    """An identity ToUnicode CMap over exactly the codepoints used."""
    ordered = sorted(codepoints)
    entries = "".join(f"<{cp:04X}> <{cp:04X}>\n" for cp in ordered)
    return (
        "/CIDInit /ProcSet findresource begin 12 dict begin begincmap\n"
        "/CMapName /Identity-Arabic def /CMapType 2 def\n"
        "1 begincodespacerange <0000> <FFFF> endcodespacerange\n"
        f"{len(ordered)} beginbfchar\n{entries}endbfchar\n"
        "endcmap CMapName currentdict /CMap defineresource pop end end"
    ).encode("latin-1")


def write_pdf(path: Path, pages: list[Page]) -> Path:
    """Write *pages* to a PDF at *path* and return it."""
    if not pages:
        raise ValueError("a PDF needs at least one page")
    codepoints = {ord(c) for page in pages for line in page.lines for c in line.text}
    cmap = _tounicode(codepoints or {0x20})

    # Object layout: 1 catalog, 2 pages, 3 font, 4 descendant, 5 descriptor,
    # 6 ToUnicode, then (page, content) pairs.
    first_page_obj = 7
    kids = " ".join(f"{first_page_obj + 2 * i} 0 R" for i in range(len(pages)))
    objects: list[bytes] = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [%s] /Count %d >>" % (kids.encode("latin-1"), len(pages)),
        b"<< /Type /Font /Subtype /Type0 /BaseFont /ArabicFixture /Encoding /Identity-H "
        b"/DescendantFonts [4 0 R] /ToUnicode 6 0 R >>",
        b"<< /Type /Font /Subtype /CIDFontType2 /BaseFont /ArabicFixture "
        b"/CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> "
        b"/FontDescriptor 5 0 R /DW %d >>" % int(ADVANCE * 1000),
        b"<< /Type /FontDescriptor /FontName /ArabicFixture /Flags 4 "
        b"/FontBBox [0 -200 1000 900] /ItalicAngle 0 /Ascent 900 /Descent -200 "
        b"/CapHeight 700 /StemV 80 >>",
        b"<< /Length %d >>\nstream\n%s\nendstream" % (len(cmap), cmap),
    ]
    for i, page in enumerate(pages):
        content = _content_stream(page)
        objects.append(
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 %d %d] "
            b"/Resources << /Font << /F1 3 0 R >> >> /Contents %d 0 R >>"
            % (page.width, page.height, first_page_obj + 2 * i + 1)
        )
        objects.append(b"<< /Length %d >>\nstream\n%s\nendstream" % (len(content), content))

    pdf = b"%PDF-1.4\n"
    offsets: list[int] = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf += b"%d 0 obj\n%s\nendobj\n" % (i, obj)
    xref_pos = len(pdf)
    count = len(objects) + 1
    pdf += b"xref\n0 %d\n0000000000 65535 f \n" % count
    for off in offsets:
        pdf += b"%010d 00000 n \n" % off
    pdf += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (count, xref_pos)
    path.write_bytes(pdf)
    return path
