"""PDF-level fixture corpus: what only a real PDF can exercise.

Each entry builds a PDF from `arabicpdf`, so the corpus is reviewable as code
rather than as committed binaries, and `tests/snapshots/*.sha256` pins the
generated bytes.

Scope is deliberately narrow: text extraction, font metrics, and the
book-level text-layer verdict. The *structuring* rules live on `OcrPage` and
are covered by `pagefixtures.py`, where the geometry is exact — routing them
through a synthetic PDF would test pdfium's line grouping as much as our own
heuristics.

Every fixture is text-layer-only on purpose: CI has no Tesseract, so a fixture
that routed to OCR could not run there.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from arabicpdf import Line, Page, to_pua, write_pdf

# Body at 12 pt, headings at 20 pt, footnotes at 8 pt — the size relations that
# heading_tiers and footnotes.split_footnotes read.
BODY, HEAD, NOTE = 12.0, 20.0, 8.0
TOP = 700        # first body line
STEP = 22        # leading between lines
INDENT = 30      # paragraph-opening indent, inset from the right margin


def _prose(texts: list[str], top: int = TOP, size: float = BODY,
           indent_first: bool = False) -> list[Line]:
    return [Line(t, top - i * STEP, size, indent=INDENT if (indent_first and i == 0) else 0)
            for i, t in enumerate(texts)]


def clean_book() -> list[Page]:
    """A healthy scholarly text layer: heading, prose, a second indented paragraph."""
    return [
        Page(lines=[
            Line("الفصل الأول", 730, HEAD, align="center"),
            *_prose([
                "الحمد لله رب العالمين والصلاة والسلام على أشرف المرسلين",
                "أما بعد فهذا كتاب جمعت فيه ما تفرق من أخبار الأمم السالفة",
                "ورتبته على أبواب ليسهل على القارئ تناوله والرجوع إليه",
            ]),
            *_prose([
                "وقد اعتمدت في ذلك على أوثق المصادر التي وقفت عليها",
                "مما رواه الثقات من أهل العلم بالتاريخ والسير والأخبار",
            ], top=TOP - 4 * STEP, indent_first=True),
        ]),
        Page(lines=[
            Line("الفصل الثاني", 730, HEAD, align="center"),
            *_prose([
                "ذكر أهل السير أن العرب كانت تنزل هذه الديار منذ القدم",
                "وكانوا يتنقلون بين المشاتي والمصايف طلبا للكلأ والماء",
                "ولهم في ذلك أخبار مشهورة أوردها المؤرخون في كتبهم",
            ]),
        ]),
    ]





def pua_book() -> list[Page]:
    """A legacy non-Unicode font: glyphs render, codepoints mean nothing.

    `bad_glyph_ratio` must reject this at any page length, so the book routes
    away from the text layer rather than emitting private-use garbage.
    """
    return [
        Page(lines=[
            Line(to_pua(ln.text), ln.y, ln.size, ln.align, ln.indent, ln.ltr)
            for ln in page.lines
        ])
        for page in clean_book()
    ]



@dataclass(frozen=True)
class Fixture:
    name: str
    build: Callable[[], list[Page]]
    description: str
    #: False when the book is meant to be *rejected* and routed to OCR. Those
    #: fixtures are snapshotted for their routing decision only — converting
    #: them would need an OCR engine CI does not have.
    text_layer_usable: bool = True


CORPUS: tuple[Fixture, ...] = (
    Fixture("clean_book", clean_book, "healthy text layer: headings, prose, indented paragraph"),
    Fixture("pua_book", pua_book, "private-use glyphs: a meaningless text layer",
            text_layer_usable=False),
)


def build_fixture(fixture: Fixture, directory: Path) -> Path:
    """Write *fixture* into *directory* and return the PDF path."""
    directory.mkdir(parents=True, exist_ok=True)
    return write_pdf(directory / f"{fixture.name}.pdf", fixture.build())
